### PR TITLE
Add possibility to change umask with environment variable

### PR DESCRIPTION
**Pull request by SirFerdek**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by thelamer** [comment]
We template our readme files please add the information to the readme-vars.yml file.

**Comment by SirFerdek** [comment]
Should be ok now, sry ;)

**Comment by thelamer** [comment]
@SirFerdek 
Now that you know the complete format we need PRs across all of these branches to keep everything uniform: 
https://github.com/linuxserver/docker-lidarr
https://github.com/linuxserver/docker-lidarr/tree/preview
https://github.com/linuxserver/docker-sonarr/tree/5.14
https://github.com/linuxserver/docker-sonarr/tree/develop
https://github.com/linuxserver/docker-sonarr/tree/preview
https://github.com/linuxserver/docker-radarr/tree/5.14
https://github.com/linuxserver/docker-radarr/tree/nightly
https://github.com/linuxserver/docker-radarr/tree/preview
https://github.com/linuxserver/docker-bazarr/pull/26 (just needs to be updated to the optional style added here) 
https://github.com/linuxserver/docker-bazarr/tree/development

**Comment by SirFerdek** [comment]
@thelamer 
Delivered, as requested.
You have in total 12 pull requests open now - merry merging.

**Comment by thelamer** [comment]
Thanks!

**Pull request merged**
