### PR TITLE
Added sonarr_backup folder in tmp storage

### LINKED ISSUE #137: Error occurred while executing task Backup: Access to the path "/config/config.xml" or "/tmp/sonarr_backup/config.xml.partial~" is denied.
I am using `:preview` container and when I try to run application backup, it looks like the application cannot save in the "/tmp/sonarr_backup/config.xml.partial~" using the provided UID as the environment variable

### PR DESCRIPTION
**Pull request by cdemi**
This allows app to create backups. This should fix #137

### CODE REVIEW

**Comment by aptalca** [comment]
Please fill out the template and provide more info.

As is, this backup location is inside the container, which is not desirable as they will all be lost one the container is destroyed. We need to look into how sonarr actually utilizes this backup location and we may need to add it as a new mount point.

**Comment by cdemi** [comment]
@aptalca what I can see from the code that `/tmp/sonarr_backup` folder is used only temporarily for creating and zipping the backup file. Once it is ready it's moved to the `/config/Backups` folder which is already a mount point.

Can you provide me with the template that I need to fill out please?

**Comment by j0nnymoe** [comment]
@cdemi the template is pre-filled when you open a PR.

**Comment by aptalca** [comment]
Per https://github.com/linuxserver/docker-sonarr/issues/137#issuecomment-554542182 this PR is unnecessary. `/tmp` has write perms for others and sonarr automatically creates that folder. Backups are done successfully in our tests

**Pull request closed without merging**
