### PR TITLE
Add python3 support

### PR DESCRIPTION
**Pull request by thebaconguy**
With the growing number of custom scripts out there it should be way past due to finally add python3 support to the sonarr/radarr/lidarr images. I'm using this locally from a fork and working wonderfully, but surely I cannot be the only in need of python3 with its growing adoption and support. 

If there is a higher level docker image that this should be pulled into and then propagated down to the sonarr/radarr/lidarr images, please let me know.

Just trying to give back to the team who builds and maintains the best images in the nine realms. :)

### CODE REVIEW

**Comment by thebaconguy** [comment]
@sparklyballs not sure who else to tag to have this looked at (or even consider if it's on the radar). Thanks for your help!

**Comment by aptalca** [comment]
We'll look into it. Until then, you can always map a local file named 80-config into the /etc/cont-init.d/ folder through your docker create or compose yml with the content "apk add --no-cache python3" so it installs it on every container start.

**Comment by thebaconguy** [comment]
@aptalca  oh neat trick! not the most ideal but saves from having to sync a fork for a one-liner. thanks for the tip!

**Comment by thelamer** [comment]
We need examples of highly consumed scripts in order to implement this base image wide. 
If it is a small section of use cases then we do offer the ability to run custom scripts now in the image startup by placing files in : 
```
/config/custom-init-scripts
```
Be aware this feature is in beta and will be moving to a new directory likely within the month: 
```
/config/custom-cont-init.d
```
Also we have finalized modification logic that can be added as a tarball from dockerhub here: 

https://github.com/linuxserver/docker-mods

The mod method would allow you to install your plugins etc in the image and share that with other users outside of just personal use. 

I will be closing this issue, but if you do have a strong case for including these deps in the base image please feel free to share.

**Pull request closed without merging**
